<h1><?php
$this->getCatalogSession()->setMyName('Mageplazas');
echo $block->getCatalogSession()->getMyName();
echo "<br><br>";
echo $this->getHelloWorldTxt(); ?></h1>

//$product = $this->productFactory->create();
//return $product->load($product->getIdBySku($sku));
//
//echo $product->getEntityId() . '<br>';
//echo $product->getName() . '<br>';
//echo $product->getSKU() . '<br>';
//echo $product->getPrice() . '<br>';
//echo $product->getSpecialPrice() . '<br>';
//echo $product->getTypeId() . '<br>';
//echo $product->getProductUrl() . '<br>';